In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
array_list = np.array(object=list_, dtype=int)
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_ after change:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list after change:")
for element in array_list:
    print(type(element))


Data types of elements in list_ after change:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list after change:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [5]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [11]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
